apiVersion: apps/v1
kind: Deployment
metadata:
        name: web-deploy
        labels:
                app: web
spec:
        selector:
                matchLabels:
                        app: web
        replicas: 10
        minReadySeconds: 5
        strategy:
                type: RollingUpdate
                rollingUpdate:
                        maxUnavailable: 0
                        maxSurge: 1
        template:
                metadata:
                        labels:
                                app: web
                spec:
                        terminationGracePeriodSeconds: 1
                        containers:
                        - name: java-pod
                          image: saparay/ticket-system-backend:0.2.RELEASE
                          ports:
                          - containerPort: 8080

